### 1. create clinic
POST http://localhost:8181/patient?clinicId=
Content-Type: application/json

{
  "name": "Ozod",
  "surname": "Ahmedov",
  "phone": "+998991112233",
  "age": 30
}

### 2. get clinic by id
GET http://localhost:8181/patient/

### 3. get all clinic
GET http://localhost:8181/patient

### 3. update clinic
PUT http://localhost:8181/patient/
Content-Type: application/json

{
  "name": "",
  "address": "",
  "phone": "",
  "imageId": ""
}

### 5. delete clinic by id
DELETE http://localhost:8181/patient/

### 6. get pagination
GET http://localhost:8181/patient/pagination/page=1&size=4
